import 'dart:convert';
import 'dart:io';

import 'DirectoryUploadState.dart';

/// Implementations of this interface are used to lookup a
/// [fingerprint] with the corresponding [directory].
///
/// This functionality is used to allow resuming uploads.
abstract class DirectoryUploadStoreI {
  /// Store a new [fingerprint] and its [uploadState].
  Future<void> set(String fingerprint, UploadState uploadState);

  /// Retrieve an [UploadState] for a [fingerprint].
  /// If no matching entry is found this method will return null.
  Future<UploadState?> get(String fingerprint);

  /// Remove an entry from the store using an upload's [fingerprint].
  Future<void> remove(String fingerprint);
}

/// This class is used to lookup a [fingerprint] with the
/// corresponding [file] entries in a [Map].
///
/// This functionality is used to allow resuming uploads.
///
/// This store **will not** keep the values after your application crashes or
/// restarts.
class DirectoryUploadMemoryStore implements DirectoryUploadStoreI {
  Map<String, UploadState> store = {};

  @override
  Future<void> set(String fingerprint, UploadState uploadState) async {
    store[fingerprint] = uploadState;
  }

  @override
  Future<UploadState?> get(String fingerprint) async {
    return store[fingerprint];
  }

  @override
  Future<void> remove(String fingerprint) async {
    store.remove(fingerprint);
  }
}

/// [DirectoryUploadFileStore] is used for storing upload progress locally on the device.
/// It is used by [DirectoryUploadClient] to resume uploads at correct %.
class DirectoryUploadFileStore implements DirectoryUploadStoreI {
  /// It must receive the directory to store the upload.
  DirectoryUploadFileStore(this.directory);

  /// The directory where the upload is stored.
  final Directory directory;

  /// Store a new [fingerprint] and its [uploadState]. The [fingerprint] is
  /// generated by [DirectoryUploadClient] and is used to identify the upload. Basically
  /// it's a made of the file location + file name.
  @override
  Future<void> set(String fingerprint, UploadState uploadState) async {
    try {
      final file = await _getFile(fingerprint);
      final uploadStateString = await _encodeMap(uploadState);
      await file.writeAsString(uploadStateString, mode: FileMode.writeOnly, flush: true);
    } catch (e, stackTrace) {
      // TODO: implement error handling
      print('An error occurred: $e');
      print('Stack trace: $stackTrace');
      throw e;
    }
  }

  /// Retrieve an [UploadState] for a [fingerprint].
  /// If no matching entry is found this method will return `null`.
  @override
  Future<UploadState?> get(String fingerprint) async {
    try {
      final file = await _getFile(fingerprint);
      if (file.existsSync()) {
        return _decodeMap(await file.readAsString());
      }
      return null;
    } catch (e, stackTrace) {
      // TODO: implement error handling
      print('An error occurred: $e');
      print('Stack trace: $stackTrace');
      throw e;
    }
  }

  /// Remove an entry from the store using an upload's [fingerprint].
  @override
  Future<void> remove(String fingerprint) async {
    try {
      final file = await _getFile(fingerprint);

      if (file.existsSync()) {
        file.deleteSync();
      }
    } catch (e, stackTrace) {
      // TODO: implement error handling
      print('An error occurred: $e');
      print('Stack trace: $stackTrace');
      throw e;
    }
  }

  Future<File> _getFile(String fingerprint) async {
    try {
      final filePath = '${directory.absolute.path}/$fingerprint';
      return File(filePath);
    } catch (e, stackTrace) {
      // TODO: implement error handling
      print('An error occurred: $e');
      print('Stack trace: $stackTrace');
      throw e;
    }
  }

  Future<String> _encodeMap(UploadState uploadState) async {
    try {
      final uploadStateJson = uploadState.toJson();
      return jsonEncode(uploadStateJson);
    }  catch (e, stackTrace) {
      // TODO: implement error handling
      print('An error occurred: $e');
      print('Stack trace: $stackTrace');
      throw e;
    }
  }

  Future<UploadState> _decodeMap(String uploadStateString) async {
    try {
      final uploadStateJson = jsonDecode(uploadStateString) as Map<String, dynamic>;
      return UploadState.toObject(uploadStateJson);
    }  catch (e, stackTrace) {
      // TODO: implement error handling
      print('An error occurred: $e');
      print('Stack trace: $stackTrace');
      throw e;
    }
  }
}
